### ISSUE TITLE
Replace altool with notarytool

### ISSUE THREAD

**Issue by Aleksid1** [rednoah/notarize-app#5]
Hi,
Can you replace altool with a new notarytool?
Apple shows a warning: "altool has been deprecated and, starting in fall 2023, will no longer be supported by the Apple notary service. You should start using notarytool to notarize your software. (-1030)"

**Comment by rednoah** [comment]
`notarize-app` is used in production so we won't make any changes for the time being because everything works perfectly in our current build environment.

We will look into `notarytool` when `altool` stops working. A quick glance at the `notarytool` man page suggests that our little `notarize-app` script will become mostly obsolete due to Apple wisely (better late than never) adding a `--wait` option.

**Comment by Aleksid1** [comment]
Thanks for your quick reply. I agree. I'll learn notarytool.
